services:
  resume-flow:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - resume-flow-workspace:/workspace
    ports:
      - "8501:8501"
    command: >
      sh -c "
      [ -f packages.txt ] && sudo apt update && sudo apt upgrade -y && sudo xargs apt install -y < packages.txt;
      [ -f requirements.txt ] && pip3 install --user -r requirements.txt;
      pip3 install --user streamlit;
      streamlit run web_app.py --server.enableCORS false --server.enableXsrfProtection false
      "
volumes:
  resume-flow-workspace: